### ISSUE TITLE
Figure out the license of AN0042

### ISSUE THREAD

**Issue by mithro** [im-tomu/tomu-bootloader#1]
The bootloader on the SiLabs is the AN0042
- https://www.silabs.com/Support%20Documents/TechnicalDocs/AN0042.pdf
- http://www.silabs.com/Support%20Documents/Software/AN0042SW.zip

We probably want to use this as the basis for our bootloader.

**Comment by xobs** [comment]
Is this still an issue?  Or do we not care about this anymore?

**Comment by mithro** [comment]
Actually, we had already fixed it out and we don't care anymore!
