### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by gl-sergei** [im-tomu/tomu-bootloader#21]
toboot being a great software using much of it's code from other projects. Some parts like `vectors.c` look much like borrowed from ChibiOS which is GPLv3. Others, like `usb_dev.c` look much like taken from https://github.com/im-tomu/chopstx/blob/efm32/mcu/usb-efm32.c which is also GPLv3, but contain wrong attribution for `Teensyduino Core Library` for some reason. There are parts (`mcu.h`) copied from Gecko SDK. It pretty much requires toboot to be licensed as GPLv3.

I think it would be great to put COPYING or LICENSE file into the project directory.

**Comment by xobs** [comment]
The last two commits should address the issue.  Thank you for pointing it out!
