### ISSUE TITLE
Remove the old Silicon Labs bootloader

### ISSUE THREAD

**Issue by mithro** [im-tomu/tomu-bootloader#25]
The DFU bootloader is better in every way;
 * It is half the size
 * It doesn't need drivers on Windows / Linux / etc
 * It's open source
 * It compiles with GCC

**Comment by kitlith** [comment]
would it be worth having a 'legacy branch' that holds the last state of the scilabs bootloader and then deleting the scilabs bootloader from master? that way it's not difficult to access if you really need it, but it can be removed from the master branch.

**Comment by mithro** [comment]
@kitling we could create a `tomu-bootloader-old` and mark it as "archived"?

**Comment by kitlith** [comment]
you could make another repository and mark it as archived, sure. just depends on the approach you want to take.

**Comment by xobs** [comment]
The old bootloader has been moved to the `an0042` branch, and removed from `master`.
