### ISSUE TITLE
Update the openocd / blackmagic flashing documentation to refer to toboot

### ISSUE THREAD

**Issue by mithro** [im-tomu/tomu-bootloader#26]
Currently they talk about the old Silicon Labs bootloader.

**Comment by kitlith** [comment]
As of #30 being merged, openocd scripts now refer to toboot. I didn't see any documentation in there that was specific to scilabs/toboot.

The documentation in the blackmagicprobe directory also doesn't seem to reference any bootloader in particular.

This issue should perhaps be renamed or closed.
