### ISSUE TITLE
The dfu bootloader flash pattern looks identical to blinky

### ISSUE THREAD

**Issue by mithro** [im-tomu/tomu-bootloader#27]
Makes it very hard to tell which mode you are in.

**Comment by kitlith** [comment]
Suggestions off the top of my head: just blink red, or blink red and green at the same time instead of alternating.

**Comment by kitlith** [comment]
on second thought: perhaps we were always dropping into dfu mode when trying to get things working and I just missed the dfu device showing up on my computer.

**Comment by kitlith** [comment]
Yeah, it was in DFU mode and we just didn't notice at first. This issue should be closed.

**Comment by kitlith** [comment]
@xobs /@mithro pinging here again because *this is inaccurate* and should be closed.

**Comment by xobs** [comment]
Okay, thanks for the update!  Closing the issue.
