### ISSUE TITLE
Figure out how to use openocd without needing to overwrite the system file

### ISSUE THREAD

**Issue by mithro** [im-tomu/tomu-bootloader#29]
In the [setup instructions](https://github.com/im-tomu/tomu-bootloader/blob/master/openocd/README.md#setup) they say;
```shell
sudo cp raspberrypi*-native.cfg /usr/local/share/openocd/scripts/interface/
```

This is kind of bad. It would be much nicer if you didn't have to do this.

Figure out how to do that!

**Comment by kitlith** [comment]
This is done in my changes, will PR. The README should probably be more rewritten than it has been, though.
