### ISSUE TITLE
Write instructions for using openocd+RPi to flash bootloader

### ISSUE THREAD

**Issue by mithro** [im-tomu/tomu-bootloader#8]

**Comment by mithro** [comment]
@cyphar has config files which worked with my ancient RPi.

**Comment by mithro** [comment]
https://github.com/cyphar/tomu-flash

**Comment by mithro** [comment]
This is now started by @cyphar in https://github.com/im-tomu/tomu-bootloader/tree/master/openocd

**Comment by cyphar** [comment]
#12 has more information added with scripts that allow you to do things in a much more automated fashion.

**Comment by xobs** [comment]
This appears to be solved.
